"""empty message

Revision ID: f8d2d4d1106e
Revises: 0e709d3d41bb
Create Date: 2024-04-29 18:43:07.138456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8d2d4d1106e'
down_revision = '0e709d3d41bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bf_state')
    op.drop_column('users', 'bf_22nov')
    op.drop_column('users', 'sending_4_april')
    op.drop_column('users', 'sending_29_feb')
    op.drop_column('users', 'sending_25_march')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_25_march', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sending_29_feb', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sending_4_april', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bf_22nov', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bf_state', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
